name: K1ngDamien's Blog
title: K1ngDamien's Blog | A blog by an Ethical Hacker, Penetration tester and DevSecOps Ethusiast!
description: Welcome to my blog where I'll discuss a bunch of topics ranging from Capture the Flag writeups, to opinion pieces, articles and projects I've been working on.

tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
show_hero: true
menu:
  - title: Home
    url: /
  - title: About
    url: /about
  - title: Contact
    url: /contact
  - title: Feed
    url: /feed.xml
email: youremail@test.com
# See: https://disqus.com/
disqus_username: disqus_username
# Contact Form Setting
# See: https://formspree.io/
formspree_form_id: formspree_form_id
